# Site settings
baseurl = "https://taehoon02.github.io/"
languageCode = "ko"
title = "JAY HAN DEVELOPMENT BLOG"
theme = "hugo-theme-cactus-plus"
googleAnalytics = ""
# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = true

contentdir = "content"
layoutdir = "layouts"
staticdir = "static"
publishdir = "public"

[params]
	author = "Jay Han"
	description = "개발하면서 적어두고 싶은 것들을 적어두는 공간입니다."
	bio = "full of things to do"

	twitter = ""
	facebook = "taehoon02"

	enableRSS = true
	enableToc = true

	enableDisqus = true
	disqusShortname = "taehoon-blog"


	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false


	enableGoogleAnalytics = true
	enableBaiduAnalytics = false
	# Set the value to your baidu analysis code if you want to use baidu analytics
	baiduAnalytics = 'your_baidu_analysis_code'

	enableTwitterCard = true
	# The url for twitter card image, default is avatar.png in static/images directory
	twitterCardImage = ""

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""

	olderPosts = ""
	newerPosts = ""
	copyright = "&copy; 2018 Jay Han"

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = true
	tweet = ""
	share = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""


# Add additional social link entries underneath
[social]
	facebook-square = "https://www.facebook.com/taehoon02"
	# twitter-square = ""
	github-square = "https://github.com/taehoon02"
